# Generated by Django 5.2.5 on 2025-10-13 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_remove_post_categories_post_category_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=100, unique=True)),
                ("age", models.PositiveIntegerField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("novice", "Новичок"),
                            ("amateur", "Любитель"),
                            ("pro", "Профессионал"),
                        ],
                        max_length=20,
                    ),
                ),
                ("password", models.CharField(max_length=100)),
                ("wins", models.PositiveIntegerField(default=0)),
                ("losses", models.PositiveIntegerField(default=0)),
                ("ties", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name="post",
            name="category",
        ),
        migrations.RemoveField(
            model_name="post",
            name="author",
        ),
        migrations.DeleteModel(
            name="Category",
        ),
        migrations.DeleteModel(
            name="Post",
        ),
    ]
