# Generated by Django 5.2.5 on 2025-10-16 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_player_remove_post_category_remove_post_author_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="stars",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
